version: "3"
services:
  # myapp: 
  #   image: codewarsx/myapp:1.2
  #   ports:
  #     - 3002:3002
  # mongodb:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=codewarsfx
  #     - MONGO_INITDB_ROOT_PASSWORD=1234
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=codewarsfx
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_MONGODB_SERVER=mongodb

